# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-09 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20161009_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
